{% set name = "xorg-xserver-xvfb" %}
{% set version = "21.1.20" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://gitlab.freedesktop.org/xorg/xserver/-/archive/xorg-server-21.1.20/xserver-xorg-server-21.1.20.tar.gz
  sha256: dac440fda99ffcaae48e51b4724013f930868ebbbf5c382b73bb36b411cdaa9c
  

build:
  number: 0
  noarch: python

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - meson
    - cmake
    - xorg-xproto
    - xorg-xorgproto
    - xorg-xtrans
    - pixman
    - libxkbfile
  host:
    - python
    - pip
    - xorg-xproto
    - xorg-xorgproto
    - xorg-xtrans
    - pixman
    - libxkbfile
  run:
    - python

test:
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://www.x.org/
  summary: Virtual framebuffer X server
  description: |
    Xvfb is an X server that can run on machines with no display hardware and no
    physical input devices. It emulates a dumb framebuffer using virtual memory.
  license: MIT
  license_family: MIT
  license_file: COPYING
  dev_url: https://gitlab.freedesktop.org/xorg/xserver
  doc_url: https://www.x.org/wiki/Documentation/

extra:
  recipe-maintainers:
    - Jrice1317
